"""Write the built-in example meshes (blackbody/assets/meshes/*.obj), built from overlapping boxes.
Overlaps are fine: Blackbody decides inside and outside by winding number, not by a clean surface."""
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / 'blackbody' / 'assets' / 'meshes'

# armchair, metres, y up, front toward +z: (centre), (half sizes)
ARMCHAIR = [
    ((0.0, 0.30, 0.02), (0.36, 0.09, 0.34)),    # seat cushion
    ((0.0, 0.16, 0.0), (0.44, 0.07, 0.40)),     # base
    ((0.0, 0.62, -0.31), (0.44, 0.33, 0.09)),   # back
    ((-0.40, 0.42, 0.02), (0.07, 0.20, 0.38)),  # left arm
    ((0.40, 0.42, 0.02), (0.07, 0.20, 0.38)),   # right arm
    ((-0.38, 0.045, -0.34), (0.035, 0.045, 0.035)),
    ((0.38, 0.045, -0.34), (0.035, 0.045, 0.035)),
    ((-0.38, 0.045, 0.34), (0.035, 0.045, 0.035)),
    ((0.38, 0.045, 0.34), (0.035, 0.045, 0.035)),
]


def boxes_obj(boxes, title):
    lines = [f'# {title}: generated by tools/make_meshes.py', 'o ' + title.replace(' ', '_')]
    faces = ((0, 1, 3, 2), (4, 6, 7, 5), (0, 4, 5, 1), (2, 3, 7, 6), (0, 2, 6, 4), (1, 5, 7, 3))
    base = 1
    for (cx, cy, cz), (hx, hy, hz) in boxes:
        for sx in (-1, 1):
            for sy in (-1, 1):
                for sz in (-1, 1):
                    lines.append(f'v {cx + sx * hx:.4f} {cy + sy * hy:.4f} {cz + sz * hz:.4f}')
        for f in faces:
            lines.append('f ' + ' '.join(str(base + i) for i in f))
        base += 8
    return '\n'.join(lines) + '\n'


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / 'armchair.obj').write_text(boxes_obj(ARMCHAIR, 'armchair'), encoding='utf-8')
    print('wrote', OUT / 'armchair.obj')


if __name__ == '__main__':
    main()
