"""Write the built-in campfire mesh (blackbody/assets/meshes/firewood.obj): split logs laid in a star
over the fire bed, inside a ring of stones. Metres, y up, the bed centred on the origin. Closed,
overlapping parts are fine: Blackbody decides inside and outside by winding number.

The fire-and-liquid presets use it as the collider the hose's water splashes off (scene/both_presets.py,
whose fire emitters follow the same logs: LOGS below)."""
import math
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / 'blackbody' / 'assets' / 'meshes' / 'firewood.obj'

# logs: (end a, end b, radius), metres; laid in a loose star, their inner ends raised on each other
LOGS = [
    ((-0.42, 0.06, -0.10), (0.10, 0.13, 0.02), 0.065),
    ((0.38, 0.06, -0.22), (-0.06, 0.15, 0.05), 0.060),
    ((0.16, 0.05, 0.42), (-0.02, 0.16, -0.06), 0.055),
    ((-0.22, 0.05, 0.36), (0.06, 0.12, -0.04), 0.050),
    ((0.02, 0.05, -0.45), (0.00, 0.11, 0.06), 0.058),
]
STONES = 11
RING = 0.52


def cylinder(a, b, r, sides=12):
    a, b = np.asarray(a, float), np.asarray(b, float)
    axis = b - a
    axis /= np.linalg.norm(axis)
    u = np.cross(axis, [0.0, 1.0, 0.0])
    if np.linalg.norm(u) < 1e-6:
        u = np.cross(axis, [1.0, 0.0, 0.0])
    u /= np.linalg.norm(u)
    v = np.cross(axis, u)
    rng = np.random.default_rng(int(abs(a[0] * 1000)) + 7)
    verts = []
    for end in (a, b):
        for k in range(sides):
            t = 2 * math.pi * k / sides
            rr = r * (1.0 + 0.08 * (rng.random() - 0.5))   # split, knotted wood: not a perfect round
            verts.append(end + rr * (math.cos(t) * u + math.sin(t) * v))
    verts += [a, b]
    faces = []
    for k in range(sides):
        k2 = (k + 1) % sides
        faces.append((k, k2, sides + k2, sides + k))
        faces.append((2 * sides, k2, k))
        faces.append((2 * sides + 1, sides + k, sides + k2))
    return verts, faces


def stone(c, r, seed):
    """A lumpy icosphere."""
    t = (1 + 5 ** 0.5) / 2
    vs = [(-1, t, 0), (1, t, 0), (-1, -t, 0), (1, -t, 0), (0, -1, t), (0, 1, t), (0, -1, -t), (0, 1, -t),
          (t, 0, -1), (t, 0, 1), (-t, 0, -1), (-t, 0, 1)]
    fs = [(0, 11, 5), (0, 5, 1), (0, 1, 7), (0, 7, 10), (0, 10, 11), (1, 5, 9), (5, 11, 4), (11, 10, 2), (10, 7, 6),
          (7, 1, 8), (3, 9, 4), (3, 4, 2), (3, 2, 6), (3, 6, 8), (3, 8, 9), (4, 9, 5), (2, 4, 11), (6, 2, 10),
          (8, 6, 7), (9, 8, 1)]
    rng = np.random.default_rng(seed)
    out = []
    for p in vs:
        p = np.asarray(p, float)
        p /= np.linalg.norm(p)
        s = r * (1.0 + 0.25 * (rng.random() - 0.5))
        out.append(np.asarray(c) + p * s * np.array([1.2, 0.7, 1.0]))
    return out, fs


def main():
    parts = [cylinder(a, b, r) for a, b, r in LOGS]
    for i in range(STONES):
        ang = 2 * math.pi * (i + 0.3 * math.sin(i * 1.7)) / STONES
        parts.append(stone((RING * math.cos(ang), 0.05, RING * math.sin(ang)), 0.085, i))
    lines = ['# Campfire: logs over the bed in a ring of stones. Generated by tools/make_firewood.py', 'o firewood']
    base = 1
    for verts, faces in parts:
        for p in verts:
            lines.append(f'v {p[0]:.4f} {p[1]:.4f} {p[2]:.4f}')
        for f in faces:
            lines.append('f ' + ' '.join(str(base + i) for i in f))
        base += len(verts)
    OUT.write_text('\n'.join(lines) + '\n', encoding='utf-8')
    print('wrote', OUT)


if __name__ == '__main__':
    main()
